### ISSUE TITLE
Doku Lesen Modbus regsiter und werte bereich

### ISSUE THREAD

**Issue by OliOssi** [CommentSectionScientist/wolfsbau#10]
[Beschreibung Modus Werte Basis.pdf](https://github.com/CommentSectionScientist/wolfsbau/files/1958831/Beschreibung.Modus.Werte.Basis.pdf)
Hier meine Doku und beschreibung

**Comment by CommentSectionScientist** [comment]
Wertebereich von 16 Bit unsigned integer ist von 0 bis 65.535. range von signed integer ist von −32.768 bis 32.767 
"resierung" -> Reservierung

**Comment by CommentSectionScientist** [comment]
Im Bild unten stimmen die Grenzwerte meiner Meinung nach nicht.

**Comment by OliOssi** [comment]
[Beschreibung Modus Werte Basis.pdf](https://github.com/CommentSectionScientist/wolfsbau/files/1966723/Beschreibung.Modus.Werte.Basis.pdf)

**Comment by OliOssi** [comment]
Hallo 
gerade eine neue Version erstellt und eine Berechnung in Excel geschrieben:
[Beschreibung Modus Werte Basis V02.pdf](https://github.com/CommentSectionScientist/wolfsbau/files/1967641/Beschreibung.Modus.Werte.Basis.V02.pdf)
[project]/3_technical_offer/Modbus_PLC/CCGC-Modbus-TCP-register-list-2.12 OOS.xlsx

**Comment by CommentSectionScientist** [comment]
kann geschlossen werden. ist sehr gut erledigt worden. Dokumente in die cloud hochgeladen
