### ISSUE TITLE
Korrekte Umrechnung von Registerwert auf Messwert bei Operationen mit vorzeichenrelevanten Ergebnissen.

### ISSUE THREAD

**Issue by CommentSectionScientist** [CommentSectionScientist/wolfsbau#16]
![img_20180503_162708](https://user-images.githubusercontent.com/36775764/39582968-5b83635e-4eef-11e8-87c0-445484f77a1a.jpg)
Wie ist die korrekte Umrechnung von Registerwert auf Messwert.
Bei Operationen die kein Vorzeichen haben muss man nur den Wert mittels des Skalierungsfaktors anpassen.

Bei Operationen mit Vorzeichen (zB GRID_L1_POWER: Register 2600) wird es etwas komplizierter.
Der mM nach korrekte Lösungsweg ist:
Messwert = Registerwert - MAX_Modbus (=65535) oder Werte in der Range der Operation (also Min = -32768, Max = 32767 und das betragsweise addiert ist auch 65535) - 1.
Also zB bei GRID_L1_POWER Messwert = 44444 - 65535 - 1 = -21092

Wenn man es sich vereinfach auf zwei Zahlenstrahls vorstellt, ist es zu verstehen, siehe Anhang.

**Comment by CommentSectionScientist** [comment]
Jop genau. Die Unterscheidung hatte ich weggelassen und einfach vorausgesetzt, dass es sich um eine Operation handelt bei der es einen overflow geben kann. (Also Vorzeichen relevant):sweat_smile:

**Comment by OliOssi** [comment]
Hallo

wie besprochen:
WENN
int16
DANN
          WENN
           Registerwert > MAX_Modbus(int16) [32767]
         DANN
                 Messwert = Registerwert - MAX_Modbus(int16) -1
SONST
Messwert = Registerwert

Danach wird die Scale auf Messwert angewendet
Ergebnis: Skalierter Messwert mit EINHEIT!
